### ISSUE TITLE
Android build crashing because of "Task :react-native-svg:compileDebugJavaWithJavac FAILED"

### ISSUE THREAD

**Issue by prathusingh** [react-native-svg/react-native-svg#1723]
NB Never post screenshots of code. Post copy paste-able code if you include any.
Ignoring this will likely lead to direct closing of the issue.
Please respect the time and energy of open source maintainers.

# Bug
Android build crashing because of "Task :react-native-svg:compileDebugJavaWithJavac FAILED"
Stack trace
```
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1278 file(s) to forward-jetify. Using 4 workers...
info JS server already running.
info Installing the app...
> Task :react-native-svg:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings
27 actionable tasks: 2 executed, 25 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-svg:compileDebugJavaWithJavac'.
> Could not find tools.jar. Please check that /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home contains a valid JDK installation.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-svg:compileDebugJavaWithJavac'.
> Could not find tools.jar. Please check that /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home contains a valid JDK installation.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s

    at makeError (/Users/prathu/Projects/passion/mint/MintMobile/node_modules/execa/index.js:174:9)
    at /Users/prathu/Projects/passion/mint/MintMobile/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (/Users/prathu/Projects/passion/mint/MintMobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/prathu/Projects/passion/mint/MintMobile/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
```

```bash
react-native init CleanProject
cd CleanProject/
yarn add react-native-svg
cd ios && pod install && cd ..
modify App.js -> run the app
```

If it's still an issue with the latest versions,
please make an sscce in the clean project,
and make it available as a git repo on github.
Or as a https://snack.expo.io/ if expo has the latest version,
and / or the bug exists both in the latest version and the one used in expo and snack.

## Environment info

Run `react-native info` in your terminal and copy the results here. Also, include the *precise* version number of this library that you are using in the project

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

Issues without reproduction steps or code are likely to stall.

1. git clone https://github.com/user/rnsvg-bug-repro
2. cd rnsvg-bug-repro
3. yarn
4. yarn ios
5. yarn android
6. ...

Describe what you expected to happen:

1.
2.

## Short, Self Contained, Correct (Compilable), Example

If you are having a problem with some code and seeking help, preparing a Short, Self Contained, Correct Example (SSCCE) is very useful. But what is an SSCCE?

It is all in the name, really. Take a look at each part. The version prepared for others to see should be:

Short (Small) - Minimise bandwidth for the example, do not bore the audience.
Self Contained - Ensure everything is included, ready to go.
Correct - Copy, paste, (compile,) see is the aim.
Example - Displays the problem we are trying to solve.

http://www.sscce.org/

**Comment by CorentinHeroux** [comment]
Same mistake, did you find a solution?

**Comment by ShubhamBathe-KM** [comment]
Facing same issue any updates regarding the solution?

**Comment by gusilveiramp** [comment]
Same here... 
Trying to find a solution...

**Comment by shendypratamaa** [comment]
same here

**Comment by ShubhamBathe-KM** [comment]
I upgraded my Project's react native version as follows:-

```
"react-native": "^0.62.2"  ==> "react-native": "^0.64.2"
"react-native-svg": "^12.1.0" ==> "react-native-svg": "12.1.1"
```

It working for me now. No more app crashes after installation.

**Comment by unicornRainbows** [comment]
Is this still an issue? I feel like I may be having it with.

"react-native-svg": "^13.0.0",
 "react-native": "0.69.4"
 
 Being brave

**Comment by kristianmarkuy** [comment]
have found any solution on this?

**Comment by WoLewicki** [comment]
I copied the error's message and found this thread: https://stackoverflow.com/questions/64968851/could-not-find-tools-jar-please-check-that-library-internet-plug-ins-javaapple. It looks like not an issue connected to the library itself, but rather a problem with configuration. I'll close this issue then. Feel free to comment here if something is wrong and we can always reopen it then. Also, it would be best to have a simple reproduction of the issue if it still exists.

**Comment by bn-serhiimalyshko** [comment]
The article above helped me to fix this issue, because a forgot to update my JAVA_HOME variable in my `~/.zprofile`
You just need to add in your  `~/.zprofile` (or `~/.zshrc` or `~/.bash_profile` or `~/.bash_rc`) the following line: 
`export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home`
It also is described in react native [documentation](https://reactnative.dev/docs/environment-setup).

My `react-native` version is 0.73.4, and `react-native-svg `version is 14.1.0. Hope it can be helpful for someone else :)

**Comment by FranciscoKloganB** [comment]
> The article above helped me to fix this issue, because a forgot to update my JAVA_HOME variable in my `~/.zprofile` You just need to add in your `~/.zprofile` (or `~/.zshrc` or `~/.bash_profile` or `~/.bash_rc`) the following line: `export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home` It also is described in react native [documentation](https://reactnative.dev/docs/environment-setup).
> 
> My `react-native` version is 0.73.4, and `react-native-svg `version is 14.1.0. Hope it can be helpful for someone else :)

Unfortunatly, it didn't help me. I double checked that my `JAVA_HOME` is exported correctly since I use `asdf` package manager. It is correctly exported and echoed. My versions are actually the same as yours and I still get the error.

I'm totally new to `react-native`, `detox` and `nx` ecosystems. Don't even know where to start looking.

**Comment by akansha1907** [comment]
After exploring numerous solutions, I finally resolved the error by running the command: npm install react-native-svg@latest
my react native version: 0.76.1
react-native-sgv version: ^15.9.0
