### ISSUE TITLE
null is not an object (evaluating 'child.props')

### ISSUE THREAD

**Issue by lewisd1996** [react-native-svg/react-native-svg#1801]
# Bug

When trying to conditionally render a SVG, if the condition is false (and therefore not rendered) using 
```
      {showMessageButton && (
        <MessageIcon svgClassName="w-4 h-4 text-gray-600" />
      )}
```
The following crash happens.

`MessageIcon.tsx`:
```
import React from "react";
import { View } from "react-native";
import Svg, { Path } from "react-native-svg";

const MessageIcon = ({ svgClassName }) => {
  return (
    <View>
      <Svg className={svgClassName} viewBox="0 0 24 24">
        <Path
          fill="currentColor"
          d="M9.98999 22.78C9.38999 22.78 8.81999 22.48 8.42999 21.95L7.23001 20.35C7.23001 20.36 7.18 20.33 7.16 20.33H6.79001C3.37001 20.33 1.25 19.4 1.25 14.79V10.79C1.25 6.58001 3.82001 5.48001 5.98001 5.29001C6.22001 5.26001 6.50001 5.25 6.79001 5.25H13.19C16.81 5.25 18.73 7.17001 18.73 10.79V14.79C18.73 15.08 18.72 15.36 18.68 15.63C18.5 17.76 17.4 20.33 13.19 20.33H12.79L11.55 21.95C11.16 22.48 10.59 22.78 9.98999 22.78ZM6.79001 6.75C6.56001 6.75 6.34 6.76 6.13 6.78C3.81 6.98 2.75 8.25001 2.75 10.79V14.79C2.75 18.22 3.81001 18.83 6.79001 18.83H7.19C7.64 18.83 8.14999 19.08 8.42999 19.44L9.63 21.05C9.85001 21.35 10.13 21.35 10.35 21.05L11.55 19.45C11.84 19.06 12.3 18.83 12.79 18.83H13.19C15.73 18.83 17 17.76 17.19 15.48C17.22 15.24 17.23 15.02 17.23 14.79V10.79C17.23 8.00001 15.98 6.75 13.19 6.75H6.79001Z"
        />
        <Path
          fill="currentColor"
          d="M9.99023 14.1899C9.43023 14.1899 8.99023 13.7399 8.99023 13.1899C8.99023 12.6399 9.44023 12.1899 9.99023 12.1899C10.5402 12.1899 10.9902 12.6399 10.9902 13.1899C10.9902 13.7399 10.5502 14.1899 9.99023 14.1899Z"
        />
        <Path
          fill="currentColor"
          d="M13.1899 14.1899C12.6299 14.1899 12.1899 13.7399 12.1899 13.1899C12.1899 12.6399 12.6399 12.1899 13.1899 12.1899C13.7399 12.1899 14.1899 12.6399 14.1899 13.1899C14.1899 13.7399 13.7399 14.1899 13.1899 14.1899Z"
        />
        <Path
          fill="currentColor"
          d="M6.7998 14.1899C6.2398 14.1899 5.7998 13.7399 5.7998 13.1899C5.7998 12.6399 6.2498 12.1899 6.7998 12.1899C7.3498 12.1899 7.7998 12.6399 7.7998 13.1899C7.7998 13.7399 7.3498 14.1899 6.7998 14.1899Z"
        />
        <Path
          fill="currentColor"
          d="M17.9401 16.29C17.7401 16.29 17.5401 16.21 17.4001 16.06C17.2401 15.9 17.1701 15.67 17.2001 15.45C17.2301 15.24 17.2401 15.02 17.2401 14.79V10.79C17.2401 8.00001 15.9901 6.75 13.2001 6.75H6.80012C6.57012 6.75 6.35015 6.76 6.14015 6.78C5.92015 6.81 5.69013 6.72999 5.53013 6.57999C5.37013 6.41999 5.28012 6.20001 5.30012 5.98001C5.48012 3.82001 6.59012 1.25 10.8001 1.25H17.2001C20.8201 1.25 22.7401 3.17001 22.7401 6.79001V10.79C22.7401 15 20.1701 16.1 18.0101 16.29C17.9801 16.29 17.9601 16.29 17.9401 16.29ZM6.92015 5.25H13.1901C16.8101 5.25 18.7301 7.17001 18.7301 10.79V14.66C20.4301 14.24 21.2301 12.99 21.2301 10.79V6.79001C21.2301 4.00001 19.9801 2.75 17.1901 2.75H10.7901C8.59014 2.75 7.35015 3.55 6.92015 5.25Z"
        />
      </Svg>
    </View>
  );
};

export default MessageIcon;

```

![simulator_screenshot_DB0C3541-A5A7-4F81-8B4A-DD205EB53E02](https://user-images.githubusercontent.com/25225528/178847904-7867a185-edf2-4fdf-84a1-3c72088b307f.png)

```bash
TypeError: null is not an object (evaluating 'child.props')

This error is located at:
    in TailwindCssReactNative.NoName
    in Unknown (created by ListingSeller)
    in ListingSeller (created by Listing)
    in RCTScrollContentView (created by ScrollView)
    in RCTScrollView (created by ScrollView)
    in ScrollView (created by ScrollView)
    in ScrollView
    in Unknown
    in Unknown
    in TailwindCssReactNative.NoName
    in Unknown (created by Listing)
    in RCTSafeAreaView
    in SafeAreaView
    in TailwindCssReactNative.NoName
    in Unknown (created by Listing)
    in Listing (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by BottomTabView)
    in RCTView (created by View)
    in View (created by Screen)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by Screen)
    in Screen (created by BottomTabView)
    in RNSScreen (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by Screen)
    in MaybeFreeze (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by BottomTabView)
    in RNSScreenNavigationContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by BottomTabView)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by BottomTabView)
    in BottomTabView (created by BottomTabNavigator)
    in Unknown (created by BottomTabNavigator)
    in BottomTabNavigator (created by BottomNavigation)
    in BottomNavigation (created by App)
    in DeviceMediaProvider (created by TailwindProvider)
    in ColorSchemeProvider (created by TailwindProvider)
    in PlatformProvider (created by TailwindProvider)
    in TailwindProvider (created by App)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by App)
    in $29383e587d62412a$export$9f8ac96af4b1b2ae (created by NativeBaseProvider)
    in ToastProvider (created by NativeBaseProvider)
    in PortalProvider (created by NativeBaseProvider)
    in HybridProvider (created by NativeBaseProvider)
    in ResponsiveQueryProvider (created by NativeBaseProvider)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by NativeBaseProvider)
    in NativeBaseConfigProviderProvider (created by NativeBaseProvider)
    in NativeBaseProvider (created by App)
    in AuthProvider (created by App)
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in DevAppContainer (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
info Opening /Users/lewis/Desktop/hoardboard/node_modules/tailwindcss-react-native/dist/with-styled-children.js with code
error spawn code ENOENT
```

Library version: 12.3.9

**Comment by JimmyLam96** [comment]
I am having the same issue. Any solutions found?

**Comment by shiv-2810** [comment]
i am having the same problem

**Comment by soorajlegend** [comment]
I'm having the same issue, any solution?

**Comment by Sohaib63** [comment]
I'm having the same problem
Any solution?

**Comment by WoLewicki** [comment]
I checked the reproduction on the newest main and couldn't spot the problem. I will close this issue then. Feel free to comment here if something is wrong and we can always reopen it then.

**Comment by MordechaiCharlap** [comment]
It's because of the curly braces at line 4: 

`const MessageIcon = ({ svgClassName })`
should be 
`const MessageIcon = ( svgClassName )`

Think about it that way, becuase you implemented it the same way as implementing props:

`<User isOnline={true}/>`
you get it the same way as props:
`const User = (props)=>{}`

if you implement it the same way as route for example in react navigation:
`navigation.navigate("UserScreen", {shownUser: user}`
you add the curly braces becuase you had them before ^
`const UserScreen = ({route})=>{}`
