### ISSUE TITLE
[Android][Fabric] Crash on release application hostObject::get for prop

### ISSUE THREAD

**Issue by psycheangel** [react-native-svg/react-native-svg#1849]
Hello,

I tried using latest react-native-svg (13.0.0) with react-native 0.70-RC4, when I tried to launch release apk the apps crash.

`hostObject::get for prop "UIManager"` 
and one time the apps crash with error text
`"RNSVGPath" was not found in the UIManager`

# Bug

It works properly on debug mode

#### Unexpected behavior

application can not start on release version, bellow are stack trace from crashlytic

```bash
Fatal Exception: com.facebook.react.common.JavascriptException: Error: Exception in HostObject::get for prop 'UIManager': java.util.ConcurrentModificationException, js engine: hermes, stack:
requireModule@1:170845
getEnforcing@1:170913
anonymous@1:343508
loadModuleImplementation@1:70710
guardedLoadModule@1:70258
metroRequire@1:69886
anonymous@1:341273
loadModuleImplementation@1:70710
guardedLoadModule@1:70258
metroRequire@1:69886
anonymous@1:339570
loadModuleImplementation@1:70710
guardedLoadModule@1:70258
metroRequire@1:69886
anonymous@1:343893
loadModuleImplementation@1:70710
guardedLoadModule@1:70258
metroRequire@1:69886
anonymous@1:364372
loadModuleImplementation@1:70710
guardedLoadModule@1:70258
metroRequire@1:69886
anonymous@1:364022
loadModuleImplementation@1:70710
guardedLoadModule@1:70258
metroRequire@1:69886
anonymous@1:622653
loadModuleImplementation@1:70710
guardedLoadModule@1:70258
metroRequire@1:69886
anonymous@1:621911
loadModuleImplementation@1:70710
guardedLoadModule@1:70258
metroRequire@1:69886
anonymous@1:618220
loadModuleImplementation@1:70710
guardedLoadModule@1:70258
metroRequire@1:69886
anonymous@1:80654
loadModuleImplementation@1:70710
guardedLoadModule@1:70258
metroRequire@1:69886
anonymous@1:77126
loadModuleImplementation@1:70710
guardedLoadModule@1:70215
metroRequire@1:69886
global@1:69461

       at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:72)
       at com.facebook.jni.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:201)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
       at java.lang.Thread.run(Thread.java:764)
```

## Environment info

Run `react-native info` in your terminal and copy the results here. Also, include the *precise* version number of this library that you are using in the project

React native info output:

```bash
System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 897.61 MB / 7.89 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 26, 29, 30, 31, 32
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
      Android NDK: 23.1.7779620
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8309675
    Visual Studio: Not Found
  Languages:
    Java: 11.0.13
  npmPackages:
    @react-native-community/cli: ^9.0.0 => 9.0.0
    react: 18.1.0 => 18.1.0
    react-native: 0.70.0-rc.4 => 0.70.0-rc.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 13.0.0

## Steps To Reproduce

Issues without reproduction steps or code are likely to stall.

1. private

## Short, Self Contained, Correct (Compilable), Example
-

**Comment by WoLewicki** [comment]
Could you somehow provide a minimal repo with reproduction needed to spot the issue? Without it, it might be hard to solve the problem.

**Comment by psycheangel** [comment]
@WoLewicki sorry seems like this is not package react-native-svg problem because removing the package still creates the crash.
